/**
 * Compose the full HTML page by wrapping LLM-generated content in the GCWeb
 * shell. This function is deterministic — same input always produces the same
 * output. The shell is never regenerated by the LLM.
 */

import { head, header, footer, scripts, type Lang } from "./shell";

export interface ComposeOptions {
  /** Page <title> (without " - Canada.ca" suffix — shell adds it). */
  title: string;
  /**
   * The LLM-generated HTML. Expected shape:
   *   <nav id="wb-bc">...</nav>        (breadcrumb)
   *   <main property="mainContentOfPage" ...>...</main>
   *
   * If the LLM produces just <main>... or bare content, we still wrap it
   * safely. See extractContent().
   */
  content: string;
  lang?: Lang;
}

/**
 * Assemble a complete, valid HTML5 document. This is what gets written to
 * disk, copied to production, and rendered in the preview iframe.
 */
export function compose({
  title,
  content,
  lang = "en",
}: ComposeOptions): string {
  const cleaned = sanitizeContent(content);
  const { breadcrumb, main } = extractContent(cleaned);
  return `<!DOCTYPE html>
<html class="no-js" lang="${lang}" dir="ltr">
<head>
${head(title, lang)}
</head>
<body vocab="http://schema.org/" typeof="WebPage">
${header(lang)}
${breadcrumb}
${main}
${footer(lang)}
${scripts()}
</body>
</html>`;
}

/**
 * The LLM is instructed to emit breadcrumb + <main>. But LLMs are LLMs — they
 * sometimes skip the breadcrumb, wrap in markdown fences, or add preamble.
 * This function tolerantly pulls the two pieces out of whatever we got.
 */
export function extractContent(raw: string): {
  breadcrumb: string;
  main: string;
} {
  let s = raw.trim();

  // Strip accidental code fences
  s = s
    .replace(/^```(?:html)?\s*/i, "")
    .replace(/```\s*$/i, "")
    .trim();

  // Strip a stray DOCTYPE / html / body if the LLM went rogue
  s = s
    .replace(/<!DOCTYPE[^>]*>/i, "")
    .replace(/<html[^>]*>/i, "")
    .replace(/<\/html>/i, "")
    .replace(/<head[\s\S]*?<\/head>/i, "")
    .replace(/<body[^>]*>/i, "")
    .replace(/<\/body>/i, "")
    .trim();

  // Pull the breadcrumb if present (before <main>)
  let breadcrumb = "";
  const bcMatch = s.match(/<nav[^>]*id=["']wb-bc["'][\s\S]*?<\/nav>/i);
  if (bcMatch) {
    breadcrumb = bcMatch[0];
    s = s.replace(bcMatch[0], "").trim();
  }

  // Find <main>; if missing, wrap bare content in one.
  let main: string;
  const mainMatch = s.match(/<main[\s\S]*<\/main>/i);
  if (mainMatch) {
    main = mainMatch[0];
  } else {
    main = `<main property="mainContentOfPage" resource="#wb-main" typeof="WebPageElement" class="container">
${s}
</main>`;
  }

  // If we still have no breadcrumb, scaffold a minimal one so the page looks
  // right. The LLM should almost always supply this — this is defensive only.
  if (!breadcrumb) {
    breadcrumb = `<nav id="wb-bc" property="breadcrumb">
  <h2 class="wb-inv">You are here:</h2>
  <div class="container">
    <ol class="breadcrumb">
      <li><a href="https://www.canada.ca/en.html">Canada.ca</a></li>
    </ol>
  </div>
</nav>`;
  }

  return { breadcrumb, main };
}

/**
 * Safety net for LLM output drift.
 *
 * Custom CSS is allowed in the system prompt as a last-resort fallback when
 * GCWeb can't express a design. We do NOT strip <style> blocks or inline
 * style="" attributes here — they're part of the intentional tier-3 output.
 *
 * What we DO clean up:
 *   - External <link rel="stylesheet"> tags (the iframe can't reliably load
 *     arbitrary external CSS, and GCWeb's own stylesheet is already in the
 *     shell).
 *   - <img> tags with unresolvable src paths — rewritten to placehold.co
 *     so the preview shows a labelled placeholder instead of a broken icon.
 */
export function sanitizeContent(raw: string): string {
  let s = raw;

  // Drop <link rel="stylesheet"> — external CSS can't be relied on here.
  s = s.replace(/<link[^>]+rel=["']stylesheet["'][^>]*>/gi, "");

  // Rewrite broken <img src> values to placehold.co so the preview always
  // renders something, instead of showing a broken-image icon.
  s = s.replace(/<img\b[^>]*>/gi, (tag) => fixImageTag(tag));

  return s;
}

function fixImageTag(tag: string): string {
  const srcMatch = tag.match(/\bsrc=["']([^"']*)["']/i);
  if (!srcMatch) return tag;
  const src = srcMatch[1];

  // Accept anything that's already a full http(s) URL. Even if the host
  // doesn't resolve, at least we didn't mangle the author's intent.
  if (/^https?:\/\//i.test(src)) return tag;

  // data: URIs are fine — these are inline and will render.
  if (/^data:/i.test(src)) return tag;

  // Try to pick reasonable placeholder dimensions from width/height attrs
  // on the tag, otherwise default to a hero-ish 1200x400.
  const wMatch = tag.match(/\bwidth=["']?(\d+)["']?/i);
  const hMatch = tag.match(/\bheight=["']?(\d+)["']?/i);
  const w = wMatch ? Number(wMatch[1]) : 1200;
  const h = hMatch ? Number(hMatch[1]) : 400;

  // Pull the alt text (or a cleaned-up filename) into the placeholder caption.
  const altMatch = tag.match(/\balt=["']([^"']*)["']/i);
  const caption = (altMatch?.[1] || basename(src) || "Image")
    .slice(0, 60)
    .replace(/\s+/g, "+");

  const newSrc = `https://placehold.co/${w}x${h}?text=${caption}`;
  return tag.replace(/\bsrc=["'][^"']*["']/i, `src="${newSrc}"`);
}

function basename(path: string): string {
  const clean = path.split(/[?#]/)[0];
  const last = clean.split(/[\\/]/).pop() || "";
  // Strip common extensions for a cleaner caption
  return last.replace(/\.(jpg|jpeg|png|gif|webp|svg)$/i, "");
}
